name: Build WinForms Project


on:
  pull_request:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.400' 
    - name: Install MSBuild 4+ Minutes
      run: choco install visualstudio2019buildtools -y
    - name: Build Project
      run: |
        # Build the project
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe" "PAPS.sln" /p:Configuration=Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled app
        path: .\PAPS\bin\Release\PAPS.exe
